# Copyright (c) 2016 Intel Corporation. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

platform :ios, '8.1'
use_frameworks!

pod 'crosswalk-extension-fingerprint’, '~> 1.3'
